#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rearRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     rearLeft,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void stopMotors() {
	motor[frontLeft] = 0; //off
	motor[frontRight]= 0; //off
	motor[rearLeft]  = 0; //off
	motor[rearRight] = 0; //off
}

task main()
{

  //waitForStart();   // wait for start of tele-op phase

  while (true)
  {
	  getJoystickSettings(joystick);

	  //------------MAIN ROBOT CONTROL------------//

	  //====LEFT JOYSTICK====//

	  //***FORWARD***//

		  motor[frontLeft] = 40; //counterclockwise
		  motor[frontRight] = 40; //clockwise
		  motor[rearLeft]  = 40; //counterclockwise
		  motor[rearRight]	= 40; //clockwise

  }
}
