#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rearLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rearRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     light,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/*
-------------------TEAM 5359 TELEOP PROGRAM-------------------
main robot movement:
left stick controls left motors
right stick controls right motors

lift movement:
D-pad up moves lift up
D-pad down moves lit down

claw open/close: button 5 opens, button 6 closes

lights: hold 2 for light
*/

task main()
{

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
	  getJoystickSettings(joystick);

	  //MAIN ROBOT CONTROL
	  if (abs(joystick.joy1_y1)>10) {
		  motor[frontLeft] = joystick.joy1_y1;
		  motor[rearLeft] = joystick.joy1_y1;
		}
		if (abs(joystick.joy1_y2)>10) {
		  motor[frontRight] = joystick.joy1_y2;
		  motor[rearRight] = joystick.joy1_y2;
		}

	  //LIFT CONTROL
	  if (joystick.joy1_TopHat == 0) motor[lift] = 40; //move up with D-pad up
	  else if (joystick.joy1_TopHat == 4) motor[lift] = -40; //move down with D-pad down

	  //CLAW CONTROL
	  if (joy1Btn(5)==1) servo[claw] = 205; //open on pressing 5
	  else if (joy1Btn(6)==1) servo[claw] = 220; //close on pressing 6

		//LIGHTS ON/OFF
	  if (joy1Btn(2)==1) motor[light] = 50; //hold down 2 for lights
  }
}
