#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rearRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     rearLeft,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - FTC Team 5359 [SolinNoids] -                                      *|
|*                                           Tele-Op Program                                              *|
|*                                                                                                        *|
|*  This program is for the holonomic drive setup for the Team 5359's 2012-13 FTC Robot.                  *|
|*  This setup uses four omniwheels positions at 45 degree angles at the corners of the robot.            *|
|*  ____________________________________________________________________________________________________  *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*  ____________________________________________________________________________________________________  *|
|*                                                                                                        *|
|*                                              CONTROLS                                                  *|
|*     Main Robot Movement:                                                                               *|
|*         Left Joystick:                                                                                 *|
|*            - Up -------------> Foward                                                                  *|
|*            - Down -----------> Backward                                                                *|
|*            - Left -----------> Strafe Left                                                             *|
|*            - Right ----------> Strafe Right                                                            *|
|*            - Left+Up --------> Strafe Forward-Left                                                     *|
|*            - Right+Up -------> Strafe Forward-Right                                                    *|
|*            - Left+Down ------> Strafe Back-Left                                                        *|
|*            - Right+Down -----> Strafe Back-Right                                                       *|
|*         Right Stick:                                                                                   *|
|*            - Left -----------> Rotate Left/Anti-Clockwise                                              *|
|*            - Right ----------> Rotate Right/Clockwise                                                  *|
|*                                                                                                        *|
|*     Lift Movement:                                                                                     *|
|*            - D-Pad Up -------> Move lift up                                                            *|
|*            - D-Pad Down -----> Move lift down                                                          *|
|*                                                                                                        *|
|*     Claw Controls                                                                                      *|
|*            - Num-Button 5 ---> Claw open                                                               *|
|*            - Num-Button 6 ---> Claw close                                                              *|
|*            - Num-Button 2 ---> Lights on                                                               *|
|*            - Num-Button 4 ---> Lights off                                                              *|
|*                                                                                                        *|
\*---------------------------------------------------------------------------------------------------5359-*/

//------------------------------- ULTILITY METHODS FOR MAIN ROBOT MOVEMENT -------------------------------//

int xClock()  {return abs(joystick.joy1_x1);}	//Left joystick x-axis value; clockwise
int xAClock() {return -abs(joystick.joy1_x1);}	//Left joystick x-axis value; anti-clockwise
int yClock()  {return abs(joystick.joy1_y1);}	//Left joystick y-axis value; clockwise
int yAClock() {return -abs(joystick.joy1_y1);}	//Left joystick y-axis value; anti-clockwise

/* Normalize the left joystick x and y axis values. */
int joyNorm()
{
	return sqrt(joystick.joy1_x1^2 + joystick.joy1_y1^2);
}

/* Moves wheel motors.
 * @param:
 * 		fl: input for frontLeft motor
 * 		fr: input for frontRight motor
 * 		rl: input for rearLeft motor
 * 		rr: input for rearRight motor
 */
void moveWheels(int fl, int fr, int rl, int rr)
{
	motor[frontLeft]  = fl;
	motor[frontRight] = fr;
	motor[rearLeft]   = rl;
	motor[rearRight]  = rr;
}

/* Stops wheel motors. */
void stopMotors()
{
	motor[frontLeft]  = 0;
	motor[frontRight] = 0;
	motor[rearLeft]   = 0;
	motor[rearRight]  = 0;
}


//----------------------------------------- TELE-OP PROGRAM ---------------------------------------------//
task main()
{
   waitForStart();   // wait for start of tele-op phase

   while (true)
   {

      getJoystickSettings(joystick);

      //----------- MAIN ROBOT CONTROL -----------//

      //====LEFT JOYSTICK====//

      //*** FORWARD ***//
      if (joystick.joy1_y1>10 && abs(joystick.joy1_x1)<10 && abs(joystick.joy1_x2)<10)
      {
         motor[frontLeft]  = -abs(joystick.joy1_y1); //counterclockwise
         motor[frontRight] = abs(joystick.joy1_y1); //clockwise
         motor[rearLeft]   = -abs(joystick.joy1_y1); //counterclockwise
         motor[rearRight]	= abs(joystick.joy1_y1); //clockwise
      }

      //*** REVERSE ***//
      if (joystick.joy1_y1<-10 && abs(joystick.joy1_x1)<10 && abs(joystick.joy1_x2)<10)
      {
         motor[frontLeft]  =	 abs(joystick.joy1_y1); //counterclockwise
         motor[frontRight] = -abs(joystick.joy1_y1); //clockwise
         motor[rearLeft]   = 	 abs(joystick.joy1_y1); //counterclockwise
         motor[rearRight]  =  -abs(joystick.joy1_y1); //clockwise
      }

      //*** STRAFE LEFT ***//
      if (joystick.joy1_x1>10 && abs(joystick.joy1_y1)<10 && abs(joystick.joy1_x2)<10)
      {
         motor[frontLeft]  =  abs(joystick.joy1_x1); //counterclockwise
         motor[frontRight] = abs(joystick.joy1_x1); //clockwise
         motor[rearLeft]   = -abs(joystick.joy1_x1); //counterclockwise
         motor[rearRight]  = -abs(joystick.joy1_x1); //clockwise
      }

      //*** STRAFE RIGHT ***//
      if (joystick.joy1_x1<-10 && abs(joystick.joy1_y1)<10 && abs(joystick.joy1_x2)<10)
      {
         motor[frontLeft]  = 	-abs(joystick.joy1_x1); //counterclockwise
         motor[frontRight] = -abs(joystick.joy1_x1); //clockwise
         motor[rearLeft] 	=  abs(joystick.joy1_x1); //counterclockwise
         motor[rearRight]  = 	 abs(joystick.joy1_x1); //clockwise
      }

      //*** STRAFE UP-LEFT ***//
      if (joystick.joy1_x1<-10 && joystick.joy1_y1>10 && abs(joystick.joy1_x2)<10)
      {
         motor[frontLeft]  = 0;
         motor[frontRight] = joyNorm(); //clockwise, distance from center
         motor[rearLeft]   = joyNorm(); //counterclockwise, distance from center
         motor[rearRight]  = 0;
      }

      //*** STRAFE UP-RIGHT ***//
      if (joystick.joy1_x1>10 && joystick.joy1_y1>10 && abs(joystick.joy1_x2)<10)
      {
         motor[frontLeft]  = joyNorm(); //clockwise, distance from center
         motor[frontRight] = 0;
         motor[rearLeft]   = 0;
         motor[rearRight]  = joyNorm(); //counterclockwise, distance from center
      }

      //*** STRAFE BACK-LEFT ***//
      if (joystick.joy1_x1<-10 && joystick.joy1_y1<-10 && abs(joystick.joy1_x2)<10)
      {
         motor[frontLeft]  = joyNorm(); //clockwise, distance from center
         motor[frontRight] = 0;
         motor[rearLeft]   = 0;
         motor[rearRight]  = joyNorm(); //counterclockwise, distance from center
      }

      //*** STRAFE BACK-RIGHT ***//
      if (joystick.joy1_x1>10 && joystick.joy1_y1<-10 && abs(joystick.joy1_x2)<10)
      {
         motor[frontLeft]  = 0;
         motor[frontRight] = joyNorm(); //clockwise, distance from center
         motor[rearLeft]   = joyNorm(); //counterclockwise, distance from center
         motor[rearRight]  = 0;
      }
      //--- END LEFT JOYSTICK ---//

      /**** RIGHT JOYSTICK ****/

      //--- TURN LEFT ---//
      if (joystick.joy1_x2>10 && abs(joystick.joy1_x1)<10 && abs(joystick.joy1_y1)<10)
      {
         motor[frontLeft]  =  abs(joystick.joy1_x2); //clockwise
         motor[frontRight] = abs(joystick.joy1_x2); //clockwise
         motor[rearLeft]   =  abs(joystick.joy1_x2); //clockwise
         motor[rearRight]  =  abs(joystick.joy1_x2); //clockwise
      }

      //*** TURN RIGHT ***//
      if (joystick.joy1_x2<-10 && abs(joystick.joy1_x1)<10 && abs(joystick.joy1_y1)<10)
      {
         motor[frontLeft]  = 	-abs(joystick.joy1_x2); //counterclockwise
         motor[frontRight] = -abs(joystick.joy1_x2); //counterclockwise
         motor[rearLeft]   =  -abs(joystick.joy1_x2); //counterclockwise
         motor[rearRight]  = 	-abs(joystick.joy1_x2); //counterclockwise
      }
      //--- END RIGHT JOYSTICK ---//

      // Stop all wheels if no joystick input
      if (abs(joystick.joy1_x1)<10 && abs(joystick.joy1_y1)<10 && abs(joystick.joy1_x2)<10) stopMotors();

      //-----------END MAIN ROBOT CONTROL---------//



      //--------------LIFT CONTROL----------------//
      if (joystick.joy1_TopHat == 0) //move up with D-pad up
      {
         motor[lift1] = -50;
         motor[lift2] = -50;
      }
      else if (joystick.joy1_TopHat == 4) //move down with D-pad down
      {
         motor[lift1] = 50;
         motor[lift2] = 50;
      }
      else if (joystick.joy1_TopHat != 0 && joystick.joy1_TopHat != 4) //stop lift
      {
         motor[lift1] = 0;
         motor[lift2] = 0;
      }
      //-------------END LIFT CONTROL-------------//

      //--------------CLAW CONTROL----------------//
      if (joy1Btn(5)==1) servo[claw] = 140; //open on pressing 5
      else if (joy1Btn(6)==1) servo[claw] = 220; //close on pressing 6
      //------------END CLAW CONTROL--------------//

      //--------------LIGHTS ON/OFF---------------//
      //if (joy1Btn(2)==1) motor[light] = 50; //press 2 to turn on lights
      //if (joy1Btn(4)==1) motor[light] = 0; //press 4 to turn off lights
      //------------END LIGHTS ON/OFF-------------//
   }
}
